version: '3.8'

services:
  frontend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/courseflow-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://54.226.39.153:8000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend.0
    environment:
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=3306
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge