version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://54.226.39.153

  backend:
    build: ./backend.0
    ports:
      - "8000:8000"
    environment:
    - DATABASE_HOST=${DB_HOST}  
    - DATABASE_PORT=3306
    - DATABASE_NAME=${DB_NAME}
    - DATABASE_USER=${DB_USER}
    - DATABASE_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ~/ssl/nginx-selfsigned.crt:/ssl/nginx-selfsigned.crt:ro
      - ~/ssl/nginx-selfsigned.key:/ssl/nginx-selfsigned.key:ro
    depends_on:
      - backend
      - frontend